# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pushmark < Formula
  desc "Send push notifications to any device via simple CLI"
  homepage "https://github.com/pushmark/pushmark-cli"
  version "1.0.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/pushmark/pushmark-cli/releases/download/v1.0.3/pushmark_1.0.3_darwin_amd64.tar.gz"
      sha256 "417785ede4bb2216040a7538e7ea0169874b91720500c0e5cce82dfdd65780b1"

      def install
        bin.install "pushmark"
      end
    end
    on_arm do
      url "https://github.com/pushmark/pushmark-cli/releases/download/v1.0.3/pushmark_1.0.3_darwin_arm64.tar.gz"
      sha256 "2df7e52c9afb025d8ea58335af2e0c55cf06ef3d666ce31bf31425edcbd8d046"

      def install
        bin.install "pushmark"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pushmark/pushmark-cli/releases/download/v1.0.3/pushmark_1.0.3_linux_amd64.tar.gz"
        sha256 "554a980e805092aa0ef2e7cfde4bb71543b19646c552f4e84416167d472f55cc"

        def install
          bin.install "pushmark"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pushmark/pushmark-cli/releases/download/v1.0.3/pushmark_1.0.3_linux_arm64.tar.gz"
        sha256 "4f16f7c0e7b3133632639a7c5d22e135d27c52bbc736f86c9d14b14239fa9157"

        def install
          bin.install "pushmark"
        end
      end
    end
  end
end
